=== perpyderp/gigasaurus/schemas/CreatureSchema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Dinosaur Schema",
    "description": "To validate data for all dinosaurs given similar properties",
    "type": "object",
    "properties": {
        "name": {"type": "string"},
        "dossier": {
            "type": ["object", "null"],
            "properties": {
                "species": {"type": "string"},
                "time": {"type": "string"},
                "diet": {"type": "string"},
                "temperament": {"type": "string"},
                "wild": {"type": "string"},
                "domesticated": {"type": "string"}
            },
            "required": ["species", "time", "diet", "temperament", "wild", "domesticated"]
        },
        "base_stats_growth": {
            "type": "object",
            "properties": {
                "health": {
                    "type": "object",
                    "properties": {
                        "base": {"type": ["number", "null"]},
                        "level_increase": {
                            "type": "object",
                            "properties": {
                                "wild": {"type": ["number", "null"]},
                                "tamed": {"type": ["number", "null"]}
                            }
                        },
                        "taming_bonus": {
                            "type": "object",
                            "properties": {
                                "additive": {"type": ["number", "null"] },
                                "multiplicative": { "type": ["number", "null"] }
                            }
                        }
                    }
                },
                "stamina": {
                    "type": "object",
                    "properties": {
                        "base": {"type": ["number", "null"]},
                        "level_increase": {
                            "type": "object",
                            "properties": {
                                "wild": {"type": ["number", "null"]},
                                "tamed": {"type": ["number", "null"]}
                            }
                        },
                        "taming_bonus": {
                            "type": "object",
                            "properties": {
                                "additive": {"type": ["number", "null"] },
                                "multiplicative": { "type": ["number", "null"] }
                            }
                        }
                    }
                },
                "oxygen": {
                    "type": "object",
                    "properties": {
                        "base": {"type": ["number", "null"]},
                        "level_increase": {
                            "type": "object",
                            "properties": {
                                "wild": {"type": ["number", "null"]},
                                "tamed": {"type": ["number", "null"]}
                            }
                        },
                        "taming_bonus": {
                            "type": "object",
                            "properties": {
                                "additive": {"type": ["number", "null"] },
                                "multiplicative": { "type": ["number", "null"] }
                            }
                        }
                    }
                },
                "food": {
                    "type": "object",
                    "properties": {
                        "base": {"type": ["number", "null"]},
                        "level_increase": {
                            "type": "object",
                            "properties": {
                                "wild": {"type": ["number", "null"]},
                                "tamed": {"type": ["number", "null"]}
                            }
                        },
                        "taming_bonus": {
                            "type": "object",
                            "properties": {
                                "additive": {"type": ["number", "null"] },
                                "multiplicative": { "type": ["number", "null"] }
                            }
                        }
                    }
                },
                "weight": {
                    "type": "object",
                    "properties": {
                        "base": {"type": ["number", "null"]},
                        "level_increase": {
                            "type": "object",
                            "properties": {
                                "wild": {"type": ["number", "null"]},
                                "tamed": {"type": ["number", "null"]}
                            }
                        },
                        "taming_bonus": {
                            "type": "object",
                            "properties": {
                                "additive": {"type": ["number", "null"] },
                                "multiplicative": { "type": ["number", "null"] }
                            }
                        }
                    }
                },
                "melee": {
                    "type": "object",
                    "properties": {
                        "base": {"type": ["number", "null"]},
                        "level_increase": {
                            "type": "object",
                            "properties": {
                                "wild": {"type": ["number", "null"]},
                                "tamed": {"type": ["number", "null"]}
                            }
                        },
                        "taming_bonus": {
                            "type": "object",
                            "properties": {
                                "additive": {"type": ["number", "null"] },
                                "multiplicative": { "type": ["number", "null"] }
                            }
                        }
                    }
                },
                "movement": {
                    "type": "object",
                    "properties": {
                        "base": {"type": ["number", "null"]},
                        "level_increase": {
                            "type": "object",
                            "properties": {
                                "wild": {"type": ["number", "null"]},
                                "tamed": {"type": ["number", "null"]}
                            }
                        },
                        "taming_bonus": {
                            "type": "object",
                            "properties": {
                                "additive": {"type": ["number", "null"] },
                                "multiplicative": { "type": ["number", "null"] }
                            }
                        }
                    }
                },
                "torpidity": {
                    "type": "object",
                    "properties": {
                        "base": {"type": ["number", "null"]},
                        "level_increase": {
                            "type": "object",
                            "properties": {
                                "wild": {"type": ["number", "null"]},
                                "tamed": {"type": ["number", "null"]}
                            }
                        },
                        "taming_bonus": {
                            "type": "object",
                            "properties": {
                                "additive": {"type": ["number", "null"] },
                                "multiplicative": { "type": ["number", "null"] }
                            }
                        }
                    }
                }
            },
            "required": ["health", "stamina", "oxygen", "food", "weight", "melee", "movement", "torpidity"]
        },
        "tameable": {"type": "boolean"},
        "rideable": {"type": "boolean"},
        "breedable": {"type": "boolean"},
        "taming": {
            "type": ["object", "null"],
            "properties": {
                "method": {"type": ["string", "null"]},
                "kibble": {"type": ["string", "null"]}
            },
            "required": ["method", "kibble"]
        },
        "saddle": {
            "type": ["array", "object", "null"],
            "properties": {
                "name": {"type": ["string", "null"]},
                "engram_level": {"type": ["integer", "null"]}
            },
            "required": ["name", "engram_level"]
        },
        "rider_weaponry": {"type": "boolean"},
        "egg": {
            "type": ["object", "null"],
            "properties": {
                "name": {"type": ["string", "array"]},
                "incubation": {
                    "type": "object",
                    "properties": {
                        "range": {"type": "string"},
                        "incubation_range": {"type": "string"},
                        "incubation_time": {"type": "string"}
                    },
                    "required": ["range", "incubation_range", "incubation_time"]
                },
                "baby_time": {"type": "string"},
                "juvenile_time": {"type": "string"},
                "adolescent_time": {"type": "string"},
                "total_maturation": {"type": "string"},
                "breeding_interval": {"type": "string"}
            },
            "required": ["name", "incubation", "baby_time", "juvenile_time", "adolescent_time", "total_maturation", "breeding_interval"]
        },
        "drag_weight": {"type": ["number", "null"]},
        "cloneable": {"type": ["boolean", "null"]},
        "entity_id": {"type": ["string", "null"]}
    },
    "required": ["name", "dossier", "base_stats_growth", "tameable", "rideable", "breedable", "taming", "saddle", "rider_weaponry", "egg", "drag_weight", "cloneable", "entity_id"]
}

=== perpyderp/gigasaurus/assets/data/creatures/dinosaurs/deinonychus/data.json
{
    "name": "Deinonychus",
    "dossier": {
        "species": "Deinonychus magna pede",
        "time": "Cretaceous",
        "diet": "Carnivore",
        "temperament": "Aggressive",
        "wild": "By the time you hear the scurrying claws of the Deinonychus, it's often too late. Superior hunters, they leap from a hiding place and pounce on their prey. The Deinonychus is an agile climber as well, jumping from wall ledge to wall ledge as it seeks high vantage points to lie in wait. A hungry Deinonychus tends to be fearless and will hunt prey much larger than itself, latching onto a dinosaur's back with its sickle-shaped claws, then starting to feed before its victim is even dead. While it likes its meat fresh, a Deinonychus isn't above scavenging a carcass if no other food is available.",
        "domesticated": "Raising a Deinonychus in captivity requires an ample food supply, as they have a fast metabolism to match their high activity level. The Deinonychus is also fiercely territorial near nests with eggs, even if the eggs aren't its own. This makes breeding successive generations a hazardous process. Unless raised from eggs, they cannot be tamed; the hunter instinct of a wild Deinonychus is so strong that it reflexively pounces on a would-be master."
    },
    "base_stats_growth": {
        "health": {
            "base": 200,
            "level_increase": {
                "wild": 40,
                "tamed": 0.054
            },
            "taming_bonus": {
                "additive": 0.07
            }
        },
        "stamina": {
            "base": 150,
            "level_increase": {
                "wild": 15,
                "tamed": 0.1
            }
        },
        "oxygen": {
            "base": 150,
            "level_increase": {
                "wild": 15,
                "tamed": 0.1
            }
        },
        "food": {
            "base": 1200,
            "level_increase": {
                "wild": 120,
                "tamed": 0.1
            }
        },
        "weight": {
            "base": 140,
            "level_increase": {
                "wild": 2.8,
                "tamed": 0.04
            }
        },
        "melee": {
            "base": 30,
            "level_increase": {
                "wild": 1.5,
                "tamed": 0.017
            },
            "taming_bonus": {
                "additive": 0.07,
                "multiplicative": 0.176
            }
        },
        "movement": {
            "base": 100,
            "level_increase": {
                "wild": null,
                "tamed": 0.015
            },
            "taming_bonus": {
                "additive": 0.2
            }
        },
        "torpidity": {
            "base": 180,
            "level_increase": {
                "wild": 10.8,
                "tamed": null
            },
            "taming_bonus": {
                "additive": 0.5
            }
        }
    },
    "tameable": false,
    "rideable": true,
    "breedable": true,
    "taming": {
        "method": null,
        "kibble": "Kibble"
    },
    "saddle": {
            "name": "Deinonychus Saddle",
            "engram_level": 32
    },
    "rider_weaponry": true,
    "egg": {
        "name": [
            "Deinonychus Egg",
            "Raptor Egg"
        ],
        "incubation": {
            "range": "80 - 90 째C / 176 - 194 째F",
            "incubation_range": "85 째C / 185 째F",
            "incubation_time": "4h 59m 58.561s"
        },
        "baby_time": "3h 42m 13.333s",
        "juvenile_time": "14h 48m 53.331s",
        "adolescent_time": "18h 31m 6.664s",
        "total_maturation": "1d 13h 2m 13.328s",
        "breeding_interval": "18h - 2d"
    },
    "drag_weight": 85,
    "cloneable": true,
    "entity_id": "Deinonychus_Character_BP_C"
}

=== perpyderp/gigasaurus/assets/data/creatures/dinosaurs/ankylosaurus/data.json
{
    "name": "Ankylosaurus",
    "dossier": {
        "species": "Ankylosaurus crassacutis",
        "time": "Late Cretaceous",
        "diet": "Herbivore",
        "temperament": "Docile",
        "wild": "Unlike many of the herd animals on the Island, Ankylosaurus crassacutis tends to live in small family units. I believe they can afford to stick with smaller groups because of their incredibly thick skin, for which they're named. Despite not being among the largest of the Island's herbivores, Ankylosaurus is one of the more difficult creatures to take down. Its thick, armored skin seems to make it more than a match for several of the mid-sized predators that would otherwise hunt it. Reckless carnivores are just as likely to hurt themselves on Ankylosaurus' spikes, as they are to get hit by its tail.", 
        "domesticated": "Without a doubt, the best trait of a trained Ankylosaurus is its enormously dense tail. This tail is powerful enough to quickly shatter the resource-laden rocks of the Island. One of the wealthier human tribes on the island utilizes a squad of Ankylosaurs in its mines and quarries. The creature's affinity for metal enables it to carry raw ore at an effectively reduced weight."
    },
    "base_stats_growth": {
        "health": {
            "base": 700,
            "level_increase": {
                "wild": 140,
                "tamed": 0.054
            },
            "taming_bonus": {
                "additive": 0.07
            }
        },
        "stamina": {
            "base": 175,
            "level_increase": {
                "wild": 17.5,
                "tamed": 0.1
            }
        },
        "oxygen": {
            "base": 150,
            "level_increase": {
                "wild": 15,
                "tamed": 0.1
            }
        },
        "food": {
            "base": 3000,
            "level_increase": {
                "wild": 300,
                "tamed": 0.1
            },
            "taming_bonus": {
                "multiplicative": 0.15
            }
        },
        "weight": {
            "base": 250,
            "level_increase": {
                "wild": 5,
                "tamed": 0.04
            }
        },
        "melee": {
            "base": 50,
            "level_increase": {
                "wild": 2.5,
                "tamed": 0.017
            },
            "taming_bonus": {
                "additive": 0.14,
                "multiplicative": 0.176
            }
        },
        "movement": {
            "base": 100,
            "level_increase": {
                "wild": null,
                "tamed": 0.02
            },
            "taming_bonus": {
                "additive": 0.35
            }
        },
        "torpidity": {
            "base": 420,
            "level_increase": {
                "wild": 25.2,
                "tamed": null
            },
            "taming_bonus": {
                "additive": 0.5
            }
        }
    },
    "tameable": true,
    "rideable": true,
    "breedable": true,
    "taming": {
        "method": "Knockout",
        "kibble": "Regular"
    },
    "saddle": {
        "name": "Ankylo Saddle",
        "engram_level": 55
    },
    "rider_weaponry": true,
    "egg": {
        "name": "Ankylo Egg",
        "incubation": {
            "range": "16 - 20 째C / 61 - 68 째F",
            "incubation_range": "18 째C / 64 째F",
            "incubation_time": "2h 37m 52.927s"
        },
        "baby_time": "4h 52m 23.859s",
        "juvenile_time": "19h 29m 35.438s",
        "adolescent_time": "1d 21m 59.297s",
        "total_maturation": "2d 43m 58.594s",
        "breeding_interval": "18h - 2d"
    },
    "drag_weight": 160,
    "cloneable": true,
    "entity_id": "Ankylo_Character_BP_C"
}

=== perpyderp/gigasaurus/assets/data/creatures/dinosaurs/parasaur/data.json
{
    "name": "Parasaur",
    "dossier": {
        "species": "Parasaurolophus amphibio",
        "time": "Late Cretaceous",
        "diet": "Herbivore",
        "temperament": "Skittish",
        "wild": "Parasaurolophus amphibio has one of the more interesting adaptations of any creature I've seen on the Island. Like all Parasaur, it has a signature crest on its head. Very docile at first, I've been able to approach the creature without disturbing it. If startled, however, the creature can vocalize a distress call to the surrounding area that warns of danger. Parasaurolophus appears to be low on the food chain and is hunted by everything, creatures and humans alike, which explains its skittish nature. It is a good source of meat and hide, if you can manage to keep up with it long enough to kill it.",
        "domesticated": "Despite being what most tribes consider a relatively useless creature to tame, I once met an interesting woman who had tamed an entire herd of them. She informed me that many overlooked the creature's potential. She even graciously gifted me a fancy saddle to put on my own Parasaurolophus one day. As a relatively simple creature to domesticate, Parasaurolophus is commonly one of the first mounts a tribe will be able to acquire. Its ability to run relatively fast for lengthy intervals makes it a solid mode of medium-range transportation, though it has almost no ability to defend itself or its rider in a traditional sense. Smaller creatures, however, appear to be frightened by the horn of Parasaurolophus although it doesn't do much damage. It also has decent weight-bearing capabilities, which could prove useful for nomadic tribes as they work to establish a presence on the Island."
    },
    "base_stats_growth": {
        "health": {
            "base": 200,
            "level_increase": {
                "wild": 40,
                "tamed": 0.054
            },
            "taming_bonus": {
                "additive": 0.07
            }
        },
        "stamina": {
            "base": 450,
            "level_increase": {
                "wild": 45,
                "tamed": 0.1
            }
        },
        "oxygen": {
            "base": 150,
            "level_increase": {
                "wild": 15,
                "tamed": 0.1
            }
        },
        "food": {
            "base": 1500,
            "level_increase": {
                "wild": 150,
                "tamed": 0.1
            }
        },
        "weight": {
            "base": 480,
            "level_increase": {
                "wild": 9.6,
                "tamed": 0.04
            }
        },
        "melee": {
            "base": 12 ,
            "level_increase": {
                "wild": 0.6,
                "tamed": 0.017
            },
            "taming_bonus": {
                "additive": 0.07,
                "multiplicative": 0.176
            }
        },
        "movement": {
            "base": 100,
            "level_increase": {
                "wild": null,
                "tamed": 0.01
            },
            "taming_bonus": {
                "additive": 0.67
            }
        },
        "torpidity": {
            "base": 150,
            "level_increase": {
                "wild": 9,
                "tamed": null
            },
            "taming_bonus": {
                "additive": 0.5
            }
        }
    },
    "tameable": true,
    "rideable": true,
    "breedable": true,
    "taming": {
        "method": "Knockout",
        "kibble": "Basic"
    },
    "saddle": {
            "name": "Parasaur Saddle",
            "engram_level": 9
    },
    "rider_weaponry": true,
    "egg": {
        "name": "Parasaur Egg",
        "incubation": {
            "range": "24 - 28 째C / 75 - 82 째F",
            "incubation_range": "26 째C / 79 째F",
            "incubation_time": "1h 25m 42.446s"
        },
        "baby_time": "2h 38m 43.809s",
        "juvenile_time": "10h 34m 55.238s",
        "adolescent_time": "13h 13m 39.047s",
        "total_maturation": "1d 2h 27m 18.094s",
        "breeding_interval": "18h - 2d"
    },
    "drag_weight": 125,
    "cloneable": true,
    "entity_id": "Para_Character_BP_C"
}

=== perpyderp/gigasaurus/assets/data/creatures/dinosaurs/troodon/data.json
{
    "name": "Troodon",
    "dossier": {
        "species": "Troodon magnanimus",
        "time": "Late Cretaceous",
        "diet": "Carnivore",
        "temperament": "Nocturnally Aggressive",
        "wild": "Quite possibly the most intelligent non-human creature on the Island, Troodon magnanimus is an incredibly fast learner. It understands meaningful experiences much faster than other creatures (including humans), and its social nature means it also teaches its packmates, making them smarter too! If Troodon's cleverness didn't make it formidable, then its tactics and biology would. It specifically pack-hunts at night when we are most vulnerable, and sees humans as its primary prey. This audacity is made especially dangerous due to its serrated fangs' poison, which drains stamina from any creature, but outright paralyses humans. Thankfully, Troodon is fairly small. Were it larger, it might well have become the dominant creature of its ecosystem.",
        "domesticated": "I thought Troodon simply could not be tamed, until I finally saw a lone survivor with one. She told me that she let \"Troody\" hunt a few of her tribe's smaller creatures for sport, and it eventually started following her everywhere. It seems that while Troodon is too intelligent to fall for the rote conditioning of \"tranq-and-feed,\" it can instead gradually gain loyalty from a social approach that provides it with the opportunity to hunt. Ever since, I have wondered at the benefits which a pack of ultra-smart, bred-for-battle Troodon may bring to a tribe brave enough to earn the favor of these clever carnivores."
    },
    "base_stats_growth": {
        "health": {
            "base": 200,
            "level_increase": {
                "wild": 40,
                "tamed": 0.054
            },
            "taming_bonus": {
                "additive": 0.07
            }
        },
        "stamina": {
            "base": 150,
            "level_increase": {
                "wild": 15,
                "tamed": 0.1
            }
        },
        "oxygen": {
            "base": 150,
            "level_increase": {
                "wild": 15,
                "tamed": 0.1
            }
        },
        "food": {
            "base": 200,
            "level_increase": {
                "wild": 20,
                "tamed": 0.1
            }
        },
        "weight": {
            "base": 140,
            "level_increase": {
                "wild": 2.8,
                "tamed": 0.04
            }
        },
        "melee": {
            "base": 7,
            "level_increase": {
                "wild": 0.35,
                "tamed": 0.017
            },
            "taming_bonus": {
                "additive": 0.07,
                "multiplicative": 0.176
            }
        },
        "movement": {
            "base": 100,
            "level_increase": {
                "wild": null,
                "tamed": 0.01
            },
            "taming_bonus": {
                "additive": 0.2
            }
        },
        "torpidity": {
            "base": 180,
            "level_increase": {
                "wild": 10.8,
                "tamed": null
            },
            "taming_bonus": {
                "additive": 0.5
            }
        }
    },
    "tameable": true,
    "rideable": false,
    "breedable": true,
    "taming": {
        "method": "Passive",
        "kibble": null
    },
    "saddle": null,
    "rider_weaponry": false,
    "egg": {
        "name": "Troodon Egg",
        "incubation": {
            "range": "28 - 32 째C / 82 - 90 째F",
            "incubation_range": "30 째C / 86 째F",
            "incubation_time": "1h 8m 10.582s"
        },
        "baby_time": "2h 6m 15.757s",
        "juvenile_time": "8h 25m 3.028s",
        "adolescent_time": "10h 31m 18.785s",
        "total_maturation": "21h 2m 37.57s",
        "breeding_interval": "18h - 2d"
    },
    "drag_weight": 35,
    "cloneable": true,
    "entity_id": "Troodon_Character_BP_C"
}

=== perpyderp/gigasaurus/assets/data/creatures/fantasy/astrocetus/data.json
{
    "name": "Astrocetus",
    "dossier": null,
    "base_stats_growth": {
        "health": {
            "base": 2800,
            "level_increase": {
                "wild": 392,
                "tamed": 0.026
            },
            "taming_bonus": {
                "additive": 0.07
            }
        },
        "stamina": {
            "base": 600,
            "level_increase": {
                "wild": 30,
                "tamed": 0.05
            }
        },
        "oxygen": {
            "base": null,
            "level_increase": {
                "wild": null,
                "tamed": null
            }
        },
        "food": {
            "base": 6000,
            "level_increase": {
                "wild": 600,
                "tamed": 0.1
            },
            "taming_bonus": {
                "multiplicative": 0.25
            }
        },
        "weight": {
            "base": 2000,
            "level_increase": {
                "wild": 40,
                "tamed": 0.05
            }
        },
        "melee": {
            "base": 75,
            "level_increase": {
                "wild": 3,
                "tamed": 0.017
            },
            "taming_bonus": {
                "additive": 0.056,
                "multiplicative": 0.176
            }
        },
        "movement": {
            "base": 100,
            "level_increase": {
                "wild": null,
                "tamed": 0.01
            }
        },
        "torpidity": {
            "base": 4200,
            "level_increase": {
                "wild": 84,
                "tamed": null
            },
            "taming_bonus": {
                "additive": 0.5
            }
        }
    },
    "tameable": true,
    "rideable": true,
    "breedable": false,
    "taming": {
        "method": "Knockout",
        "kibble": "Extraordinary"
    },
    "saddle": {
        "name": "Astrocetus Tek Saddle",
        "engram_level": null
    },
    "rider_weaponry": false,
    "egg": null,
    "drag_weight": 4000,
    "cloneable": false,
    "entity_id": "SpaceWhale_Character_BP_C"
}
