=== perpyderp/gigasaurus/schemas/CreatureSchema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Dinosaur Schema",
    "description": "To validate data for all dinosaurs given similar properties",
    "type": "object",
    "properties": {
        "name": {"type": "string"},
        "dossier": {
            "type": ["object", "null"],
            "properties": {
                "species": {"type": "string"},
                "time": {"type": "string"},
                "diet": {"type": "string"},
                "temperament": {"type": "string"},
                "wild": {"type": "string"},
                "domesticated": {"type": "string"}
            },
            "required": ["species", "time", "diet", "temperament", "wild", "domesticated"]
        },
        "base_stats_growth": {
            "type": "object",
            "properties": {
                "health": {
                    "type": "object",
                    "properties": {
                        "base": {"type": ["number", "null"]},
                        "level_increase": {
                            "type": "object",
                            "properties": {
                                "wild": {"type": ["number", "null"]},
                                "tamed": {"type": ["number", "null"]}
                            }
                        },
                        "taming_bonus": {
                            "type": "object",
                            "properties": {
                                "additive": {"type": ["number", "null"] },
                                "multiplicative": { "type": ["number", "null"] }
                            }
                        }
                    }
                },
                "stamina": {
                    "type": "object",
                    "properties": {
                        "base": {"type": ["number", "null"]},
                        "level_increase": {
                            "type": "object",
                            "properties": {
                                "wild": {"type": ["number", "null"]},
                                "tamed": {"type": ["number", "null"]}
                            }
                        },
                        "taming_bonus": {
                            "type": "object",
                            "properties": {
                                "additive": {"type": ["number", "null"] },
                                "multiplicative": { "type": ["number", "null"] }
                            }
                        }
                    }
                },
                "oxygen": {
                    "type": "object",
                    "properties": {
                        "base": {"type": ["number", "null"]},
                        "level_increase": {
                            "type": "object",
                            "properties": {
                                "wild": {"type": ["number", "null"]},
                                "tamed": {"type": ["number", "null"]}
                            }
                        },
                        "taming_bonus": {
                            "type": "object",
                            "properties": {
                                "additive": {"type": ["number", "null"] },
                                "multiplicative": { "type": ["number", "null"] }
                            }
                        }
                    }
                },
                "food": {
                    "type": "object",
                    "properties": {
                        "base": {"type": ["number", "null"]},
                        "level_increase": {
                            "type": "object",
                            "properties": {
                                "wild": {"type": ["number", "null"]},
                                "tamed": {"type": ["number", "null"]}
                            }
                        },
                        "taming_bonus": {
                            "type": "object",
                            "properties": {
                                "additive": {"type": ["number", "null"] },
                                "multiplicative": { "type": ["number", "null"] }
                            }
                        }
                    }
                },
                "weight": {
                    "type": "object",
                    "properties": {
                        "base": {"type": ["number", "null"]},
                        "level_increase": {
                            "type": "object",
                            "properties": {
                                "wild": {"type": ["number", "null"]},
                                "tamed": {"type": ["number", "null"]}
                            }
                        },
                        "taming_bonus": {
                            "type": "object",
                            "properties": {
                                "additive": {"type": ["number", "null"] },
                                "multiplicative": { "type": ["number", "null"] }
                            }
                        }
                    }
                },
                "melee": {
                    "type": "object",
                    "properties": {
                        "base": {"type": ["number", "null"]},
                        "level_increase": {
                            "type": "object",
                            "properties": {
                                "wild": {"type": ["number", "null"]},
                                "tamed": {"type": ["number", "null"]}
                            }
                        },
                        "taming_bonus": {
                            "type": "object",
                            "properties": {
                                "additive": {"type": ["number", "null"] },
                                "multiplicative": { "type": ["number", "null"] }
                            }
                        }
                    }
                },
                "movement": {
                    "type": "object",
                    "properties": {
                        "base": {"type": ["number", "null"]},
                        "level_increase": {
                            "type": "object",
                            "properties": {
                                "wild": {"type": ["number", "null"]},
                                "tamed": {"type": ["number", "null"]}
                            }
                        },
                        "taming_bonus": {
                            "type": "object",
                            "properties": {
                                "additive": {"type": ["number", "null"] },
                                "multiplicative": { "type": ["number", "null"] }
                            }
                        }
                    }
                },
                "torpidity": {
                    "type": "object",
                    "properties": {
                        "base": {"type": ["number", "null"]},
                        "level_increase": {
                            "type": "object",
                            "properties": {
                                "wild": {"type": ["number", "null"]},
                                "tamed": {"type": ["number", "null"]}
                            }
                        },
                        "taming_bonus": {
                            "type": "object",
                            "properties": {
                                "additive": {"type": ["number", "null"] },
                                "multiplicative": { "type": ["number", "null"] }
                            }
                        }
                    }
                }
            },
            "required": ["health", "stamina", "oxygen", "food", "weight", "melee", "movement", "torpidity"]
        },
        "tameable": {"type": "boolean"},
        "rideable": {"type": "boolean"},
        "breedable": {"type": "boolean"},
        "taming": {
            "type": ["object", "null"],
            "properties": {
                "method": {"type": ["string", "null"]},
                "kibble": {"type": ["string", "null"]}
            },
            "required": ["method", "kibble"]
        },
        "saddle": {
            "type": ["array", "object", "null"],
            "properties": {
                "name": {"type": ["string", "null"]},
                "engram_level": {"type": ["integer", "null"]}
            },
            "required": ["name", "engram_level"]
        },
        "rider_weaponry": {"type": "boolean"},
        "egg": {
            "type": ["object", "null"],
            "properties": {
                "name": {"type": ["string", "array"]},
                "incubation": {
                    "type": "object",
                    "properties": {
                        "range": {"type": "string"},
                        "incubation_range": {"type": "string"},
                        "incubation_time": {"type": "string"}
                    },
                    "required": ["range", "incubation_range", "incubation_time"]
                },
                "baby_time": {"type": "string"},
                "juvenile_time": {"type": "string"},
                "adolescent_time": {"type": "string"},
                "total_maturation": {"type": "string"},
                "breeding_interval": {"type": "string"}
            },
            "required": ["name", "incubation", "baby_time", "juvenile_time", "adolescent_time", "total_maturation", "breeding_interval"]
        },
        "drag_weight": {"type": ["number", "null"]},
        "cloneable": {"type": ["boolean", "null"]},
        "entity_id": {"type": ["string", "null"]}
    },
    "required": ["name", "dossier", "base_stats_growth", "tameable", "rideable", "breedable", "taming", "saddle", "rider_weaponry", "egg", "drag_weight", "cloneable", "entity_id"]
}

=== perpyderp/gigasaurus/assets/data/creatures/dinosaurs/baryonyx/data.json
{
    "name": "Baryonyx",
    "dossier": {
        "species": "Baryonyx aquafulgur",
        "time": "Early Cretaceous",
        "diet": "Piscivore",
        "temperament": "Passive to land creatures, but aggressive to water-dwellers",
        "wild": "Like the Carnotaurus, Baryonyx aquafulguar is a large carnivore, but not large enough to rival the Island's apex predators. While not as powerful as some deep-sea predators or Spinosaurus, Baryonyx is an extremely fast swimmer who is still sufficiently nimble enough to threaten most creatures on the Island. And yet despite being a fast, dangerous dinosaur, Baryonyx almost exclusively consumes fish and other water-dwellers. The highly specific metabolism of Baryonyx seems to allow it to heal wounds almost preternaturally fast after feeding on nutritious fish meat. Perhaps this is why Baryonyx rarely attacks land animals?",
        "domesticated": "Baryonyx's natural affinity for aquatic predation means that once tamed; it learns to kill ocean-dwellers even more efficiently. Between its speed and its power, Baryonyx makes an ideal choice for anyone interested in frequently moving between water and land travel, and who values speed and agility over raw strength."
    },
    "base_stats_growth": {
        "health": {
            "base": 440,
            "level_increase": {
                "wild": 88,
                "tamed": 0.054
            },
            "taming_bonus": {
                "additive": 0.07
            }
        },
        "stamina": {
            "base": 325,
            "level_increase": {
                "wild": 32.5,
                "tamed": 0.1
            }
        },
        "oxygen": {
            "base": 225,
            "level_increase": {
                "wild": 22.5,
                "tamed": null
            }
        },
        "food": {
            "base": 2250,
            "level_increase": {
                "wild": 225,
                "tamed": 0.1
            }
        },
        "weight": {
            "base": 325,
            "level_increase": {
                "wild": 6.5,
                "tamed": 0.04
            }
        },
        "melee": {
            "base": 35,
            "level_increase": {
                "wild": 1.75,
                "tamed": 0.017
            },
            "taming_bonus": {
                "additive": 0.07,
                "multiplicative": 0.176
            }
        },
        "movement": {
            "base": 100,
            "level_increase": {
                "wild": null,
                "tamed": 0.01
            },
            "taming_bonus": {
                "additive": 0.2
            }
        },
        "torpidity": {
            "base": 400,
            "level_increase": {
                "wild": 24,
                "tamed": null
            },
            "taming_bonus": {
                "additive": 0.5
            }
        }
    },
    "tameable": true,
    "rideable": true,
    "breedable": true,
    "taming": {
        "method": "Knockout",
        "kibble": "Simple"
    },
    "saddle": {
        "name": "Baryonyx Saddle",
        "engram_level": 49
    },
    "rider_weaponry": true,
    "egg": {
        "name": "Baryonyx Egg",
        "incubation": {
            "range": "29 - 35 째C / 84 - 95 째F",
            "incubation_range": "32 째C / 90 째F",
            "incubation_time": "1h 59m 59.424s"
        },
        "baby_time": "4h 37m 46.666s",
        "juvenile_time": "18h 31m 6.662s",
        "adolescent_time": "23h 8m 53.328s",
        "total_maturation": "1d 22h 17m 46.656s",
        "breeding_interval": "18h - 2d"
    },
    "drag_weight": 210,
    "cloneable": true,
    "entity_id": "Baryonyx_Character_BP_C"
}

=== perpyderp/gigasaurus/assets/data/creatures/dinosaurs/pachy/data.json
{
    "name": "Pachy",
    "dossier": {
        "species": "Pachycephalosaurus leniproelia",
        "time": "Late Cretaceous",
        "diet": "Herbivore",
        "temperament": "Passive",
        "wild": "Pachycephalosaurus is a bit of a conundrum. It is a very passive (even friendly) herbivore, common to much of the Island. At the same time, it is one of the most dangerous herbivores that I have yet encountered on the Island. Its charging headbutt is a display of sheer physical power, and can kill much more quickly than you might think. While Pachycephalosaurus is generally friendly, it has a short temper. Its fight-or-flight response always seems to choose \"fight!\" The Pachy becomes extremely aggressive once attacked. Additionally, it is an incredibly fast sprinter, so escaping from an enraged Pachy is very difficult.",
        "domesticated": "Pachycephalosaurus is an excellent battle-mount for those who want to ride a smaller, nimble combatant into the fray. Because of its particular musculature, it cannot effectively carry large quantities of resources. It can, however, move with brief magnificent bursts of speed, and its headbutt is simply devastating."
    },
    "base_stats_growth": {
        "health": {
            "base": 175,
            "level_increase": {
                "wild": 35,
                "tamed": 0.054
            },
            "taming_bonus": {
                "additive": 0.07
            }
        },
        "stamina": {
            "base": 150,
            "level_increase": {
                "wild": 15,
                "tamed": 0.1
            }
        },
        "oxygen": {
            "base": 150,
            "level_increase": {
                "wild": 15,
                "tamed": 0.1
            }
        },
        "food": {
            "base": 1200,
            "level_increase": {
                "wild": 120,
                "tamed": 0.1
            }
        },
        "weight": {
            "base": 150,
            "level_increase": {
                "wild": 3,
                "tamed": 0.04
            }
        },
        "melee": {
            "base": 10,
            "level_increase": {
                "wild": 0.5,
                "tamed": 0.017
            },
            "taming_bonus": {
                "additive": 0.07,
                "multiplicative": 0.176
            }
        },
        "movement": {
            "base": 100,
            "level_increase": {
                "wild": null,
                "tamed": 0.01
            },
            "taming_bonus": {
                "additive": 0.2
            }
        },
        "torpidity": {
            "base": 160,
            "level_increase": {
                "wild": 9.6,
                "tamed": null
            },
            "taming_bonus": {
                "additive": 0.5
            }
        }
    },
    "tameable": true,
    "rideable": true,
    "breedable": true,
    "taming": {
        "method": "Knockout",
        "kibble": "Simple"
    },
    "saddle": {
            "name": "Pachy Saddle",
            "engram_level": 14
    },
    "rider_weaponry": false,
    "egg": {
        "name": "Pachy Egg",
        "incubation": {
            "range": "24 - 28 째C / 75 - 82 째F",
            "incubation_range": "26 째C / 79 째F",
            "incubation_time": "1h 25m 42.446s"
        },
        "baby_time": "2h 38m 43.809s",
        "juvenile_time": "10h 34m 55.238s",
        "adolescent_time": "13h 13m 39.047s",
        "total_maturation": "1d 2h 27m 18.094s",
        "breeding_interval": "18h - 2d"
    },
    "drag_weight": 85,
    "cloneable": true,
    "entity_id": "Pachy_Character_BP_C"
}

=== perpyderp/gigasaurus/assets/data/creatures/dinosaurs/therizinosaur/data.json
{
    "name": "Therizinosaur",
    "dossier": {
        "species": "Therizinosaurus multiensis",
        "time": "Late Cretaceous",
        "diet": "Herbivore",
        "temperament": "Aggressive",
        "wild": "I'm not entirely sure how Therizinosaurus multiensis stays populated on the Island. It is surprisingly slow for its size, and is a solitary predator (so no pack to back it up). I suppose the fact that its sheer power rivals Tyrannosaurus is the only thing that allows this very aggressive medium-sized predator to thrive. The claws of Therizinosaurus are some of the most versatile biological tools I've encountered, as adept at removing trees and foliage from Therizinosaurus' path as they are at piercing the thick shells and hide of the Island's most defensive creatures if backed into a fight.",
        "domesticated": "A tamed Therizinosaurus is one of the most versatile mounts a survivor can have. It can be trained to use its claws brutally or delicately, allowing the rider to primarily harvest with enhanced efficiency the specific kinds of resources that he or she needs. And in combat, these same claws can pierce straight through the toughest armor. This flexibility more than makes up for its inability to carry the large loads of the Island's many herbivorous beasts of burden."
    },
    "base_stats_growth": {
        "health": {
            "base": 870,
            "level_increase": {
                "wild": 174,
                "tamed": 0.054
            },
            "taming_bonus": {
                "additive": 0.07
            }
        },
        "stamina": {
            "base": 300,
            "level_increase": {
                "wild": 30,
                "tamed": 0.1
            }
        },
        "oxygen": {
            "base": 150,
            "level_increase": {
                "wild": 15,
                "tamed": 0.1
            }
        },
        "food": {
            "base": 3000,
            "level_increase": {
                "wild": 300,
                "tamed": 0.1
            }
        },
        "weight": {
            "base": 365,
            "level_increase": {
                "wild": 7.3,
                "tamed": 0.04
            }
        },
        "melee": {
            "base": 52,
            "level_increase": {
                "wild": 2.6,
                "tamed": 0.017
            },
            "taming_bonus": {
                "additive": 0.07,
                "multiplicative": 0.176
            }
        },
        "movement": {
            "base": 100,
            "level_increase": {
                "wild": null,
                "tamed": 0.01
            }
        },
        "torpidity": {
            "base": 925,
            "level_increase": {
                "wild": 55.5,
                "tamed": null
            },
            "taming_bonus": {
                "additive": 0.5
            }
        }
    },
    "tameable": true,
    "rideable": true,
    "breedable": true,
    "taming": {
        "method": "Knockout",
        "kibble": "Exceptional"
    },
    "saddle": {
            "name": "Therizinosaurus Saddle",
            "engram_level": 69
    },
    "rider_weaponry": false,
    "egg": {
        "name": "Therizino Egg",
        "incubation": {
            "range": "26 - 32 째C / 79 - 90 째F",
            "incubation_range": "29 째C / 84 째F",
            "incubation_time": "1h 39m 59.521s"
        },
        "baby_time": "11h 34m 26.666s",
        "juvenile_time": "1d 22h 17m 46.662s",
        "adolescent_time": "2d 9h 52m 13.328s",
        "total_maturation": "4d 19h 44m 26.656s",
        "breeding_interval": "18h - 2d"
    },
    "drag_weight": 250,
    "cloneable": true,
    "entity_id": "Therizino_Character_BP_C"
}

=== perpyderp/gigasaurus/assets/data/creatures/dinosaurs/yutyrannus/data.json
{
    "name": "Yutyrannus",
    "dossier": {
        "species": "Yutyrannus saevus",
        "time": "Cretaceous",
        "diet": "Carnivore",
        "temperament": "Aggressive",
        "wild": "The Yutyrannus saevus is believed to be related to the Tyrannosaurus rex, but it is noticeably different upon first glance. Feathered creatures are not necessarily viewed as dangerous predators in the same light as other theropods. However, the Yutyrannus strikes fear into even the Island's most skilled hunters. There are few wild predators that are able to pack-hunt alongside the generally hostile Carnotaurus, like the Yutyrannus does, with such ease. It is also the only creature I've seen to consistently induce a state of panic in opponents with its roar. Upon hearing it, most creatures in the area will flee for safety.",
        "domesticated": "A domesticated Yutyrannus can be a powerful offensive or defensive addition to war parties. With its mighty roar, it can induce fear in opposing creatures. Meanwhile, Yutyrannus can be trained to develop a confidence-boosting Battle-Cry which counteracts enemy attempts to induce fear, while also bolstering the resolve of allies, and may even draw wild Carnotaurus to its aid. These unique \"leadership\" qualities make the Yutyrannus a versatile, and at times, a necessary creature to have on your side during large-scale confrontations!"
    },
    "base_stats_growth": {
        "health": {
            "base": 1100,
            "level_increase": {
                "wild": 220,
                "tamed": 0.054
            },
            "taming_bonus": {
                "additive": 0.07
            }
        },
        "stamina": {
            "base": 420,
            "level_increase": {
                "wild": 42,
                "tamed": 0.1
            }
        },
        "oxygen": {
            "base": 150,
            "level_increase": {
                "wild": 15,
                "tamed": 0.1
            }
        },
        "food": {
            "base": 3000,
            "level_increase": {
                "wild": 300,
                "tamed": 0.1
            }
        },
        "weight": {
            "base": 500,
            "level_increase": {
                "wild": 10,
                "tamed": 0.04
            }
        },
        "melee": {
            "base": 55,
            "level_increase": {
                "wild": 2.75,
                "tamed": 0.017
            },
            "taming_bonus": {
                "additive": 0.07,
                "multiplicative": 0.176
            }
        },
        "movement": {
            "base": 100,
            "level_increase": {
                "wild": null,
                "tamed": 0.01
            }
        },
        "torpidity": {
            "base": 1550,
            "level_increase": {
                "wild": 93,
                "tamed": null
            },
            "taming_bonus": {
                "additive": 0.5
            }
        }
    },
    "tameable": true,
    "rideable": true,
    "breedable": true,
    "taming": {
        "method": "Knockout",
        "kibble": "Extraordinary"
    },
    "saddle": {
            "name": "Yutyrannus Saddle",
            "engram_level": 80
    },
    "rider_weaponry": false,
    "egg": {
        "name": "Yutyrannus Egg",
        "incubation": {
            "range": "32 - 34 째C / 90 - 93 째F",
            "incubation_range": "33 째C / 91 째F",
            "incubation_time": "4h 59m 58.561s"
        },
        "baby_time": "18h 31m 6.662s",
        "juvenile_time": "3d 2h 4m 26.65s",
        "adolescent_time": "3d 20h 35m 33.313s",
        "total_maturation": "7d 17h 11m 6.625s",
        "breeding_interval": "18h - 2d"
    },
    "drag_weight": 500,
    "cloneable": true,
    "entity_id": "Yutyrannus_Character_BP_C"
}

=== perpyderp/gigasaurus/assets/data/creatures/dinosaurs/kentrosaurus/data.json
{
    "name": "Kentrosaurus",
    "dossier": {
        "species": "Kentrosaurus Aethiopicus",
        "time": "Late Jurassic",
        "diet": "Herbivore",
        "temperament": "Short-Tempered",
        "wild": "While Kentrosaurus aethiopicus is considerably smaller than its close relative, Stegosaurus regium, it is much more formidable in matters of self-defense. In fact, it is arguably the pound for pound champion of not only the Stegosaurus, but when encountered in close-knit fighting packs, ranks atop the Island's herbivorous dinosaurs in general. Thanks to its wickedly sharp defensive spikes, any creature that attacks Kentrosaurus is likely to be reversely wounded in turn, and it is capable of piercing even the thickest of hides and armors when it goes on the offensive. I have personally witnessed the Kentrosaurus fell much larger predators in a single such \"impaling\" maneuver! Underestimating Kentrosaurus can be a fatal mistake, particularly when it is in a herd. When travelling in numbers, Kentrosaurus seems to grow much more aggressive, increasing the range at which it will defend its territory.",
        "domesticated": "Survivors have seen little success in their attempts to ride Kentrosaurus, owing to its spikes and hot-headed temperament. However, a tamed herd of Kentrosaurus can effectively defend a compound and take on larger carnivores. Once impaled by its attack, the Kentrosaurus slams the attacker on the ground continuously, helping to turn the tide of a pitched battle!"
    },
    "base_stats_growth": {
        "health": {
            "base": 650,
            "level_increase": {
                "wild": 130,
                "tamed": 0.054
            },
            "taming_bonus": {
                "additive": 0.07
            }
        },
        "stamina": {
            "base": 300,
            "level_increase": {
                "wild": 30,
                "tamed": 0.1
            }
        },
        "oxygen": {
            "base": 150,
            "level_increase": {
                "wild": 15,
                "tamed": 0.1
            }
        },
        "food": {
            "base": 6000,
            "level_increase": {
                "wild": 600,
                "tamed": 0.1
            }
        },
        "weight": {
            "base": 500,
            "level_increase": {
                "wild": 10,
                "tamed": 0.04
            }
        },
        "melee": {
            "base": 42,
            "level_increase": {
                "wild": 2.1,
                "tamed": 0.017
            },
            "taming_bonus": {
                "additive": 0.07,
                "multiplicative": 0.176
            }
        },
        "movement": {
            "base": 100,
            "level_increase": {
                "wild": null,
                "tamed": 0.01
            }
        },
        "torpidity": {
            "base": 500,
            "level_increase": {
                "wild": 30,
                "tamed": null
            },
            "taming_bonus": {
                "additive": 0.5
            }
        }
    },
    "tameable": true,
    "rideable": false,
    "breedable": true,
    "taming": {
        "method": "Knockout",
        "kibble": "Regular"
    },
    "saddle": null,
    "rider_weaponry": true,
    "egg": {
        "name": "Kentro Egg",
        "incubation": {
            "range": "24 - 30 째C / 75 - 86 째F",
            "incubation_range": "27 째C / 81 째F",
            "incubation_time": "2h 46m 39.2s"
        },
        "baby_time": "5h 8m 38.517s",
        "juvenile_time": "20h 34m 34.069s",
        "adolescent_time": "1d 1h 43m 12.586s",
        "total_maturation": "2d 3h 26m 25.172s",
        "breeding_interval": "18h - 2d"
    },
    "drag_weight": 250,
    "cloneable": true,
    "entity_id": "Kentro_Character_BP_C"
}
