=== perpyderp/gigasaurus/schemas/CreatureSchema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Dinosaur Schema",
    "description": "To validate data for all dinosaurs given similar properties",
    "type": "object",
    "properties": {
        "name": {"type": "string"},
        "dossier": {
            "type": ["object", "null"],
            "properties": {
                "species": {"type": "string"},
                "time": {"type": "string"},
                "diet": {"type": "string"},
                "temperament": {"type": "string"},
                "wild": {"type": "string"},
                "domesticated": {"type": "string"}
            },
            "required": ["species", "time", "diet", "temperament", "wild", "domesticated"]
        },
        "base_stats_growth": {
            "type": "object",
            "properties": {
                "health": {
                    "type": "object",
                    "properties": {
                        "base": {"type": ["number", "null"]},
                        "level_increase": {
                            "type": "object",
                            "properties": {
                                "wild": {"type": ["number", "null"]},
                                "tamed": {"type": ["number", "null"]}
                            }
                        },
                        "taming_bonus": {
                            "type": "object",
                            "properties": {
                                "additive": {"type": ["number", "null"] },
                                "multiplicative": { "type": ["number", "null"] }
                            }
                        }
                    }
                },
                "stamina": {
                    "type": "object",
                    "properties": {
                        "base": {"type": ["number", "null"]},
                        "level_increase": {
                            "type": "object",
                            "properties": {
                                "wild": {"type": ["number", "null"]},
                                "tamed": {"type": ["number", "null"]}
                            }
                        },
                        "taming_bonus": {
                            "type": "object",
                            "properties": {
                                "additive": {"type": ["number", "null"] },
                                "multiplicative": { "type": ["number", "null"] }
                            }
                        }
                    }
                },
                "oxygen": {
                    "type": "object",
                    "properties": {
                        "base": {"type": ["number", "null"]},
                        "level_increase": {
                            "type": "object",
                            "properties": {
                                "wild": {"type": ["number", "null"]},
                                "tamed": {"type": ["number", "null"]}
                            }
                        },
                        "taming_bonus": {
                            "type": "object",
                            "properties": {
                                "additive": {"type": ["number", "null"] },
                                "multiplicative": { "type": ["number", "null"] }
                            }
                        }
                    }
                },
                "food": {
                    "type": "object",
                    "properties": {
                        "base": {"type": ["number", "null"]},
                        "level_increase": {
                            "type": "object",
                            "properties": {
                                "wild": {"type": ["number", "null"]},
                                "tamed": {"type": ["number", "null"]}
                            }
                        },
                        "taming_bonus": {
                            "type": "object",
                            "properties": {
                                "additive": {"type": ["number", "null"] },
                                "multiplicative": { "type": ["number", "null"] }
                            }
                        }
                    }
                },
                "weight": {
                    "type": "object",
                    "properties": {
                        "base": {"type": ["number", "null"]},
                        "level_increase": {
                            "type": "object",
                            "properties": {
                                "wild": {"type": ["number", "null"]},
                                "tamed": {"type": ["number", "null"]}
                            }
                        },
                        "taming_bonus": {
                            "type": "object",
                            "properties": {
                                "additive": {"type": ["number", "null"] },
                                "multiplicative": { "type": ["number", "null"] }
                            }
                        }
                    }
                },
                "melee": {
                    "type": "object",
                    "properties": {
                        "base": {"type": ["number", "null"]},
                        "level_increase": {
                            "type": "object",
                            "properties": {
                                "wild": {"type": ["number", "null"]},
                                "tamed": {"type": ["number", "null"]}
                            }
                        },
                        "taming_bonus": {
                            "type": "object",
                            "properties": {
                                "additive": {"type": ["number", "null"] },
                                "multiplicative": { "type": ["number", "null"] }
                            }
                        }
                    }
                },
                "movement": {
                    "type": "object",
                    "properties": {
                        "base": {"type": ["number", "null"]},
                        "level_increase": {
                            "type": "object",
                            "properties": {
                                "wild": {"type": ["number", "null"]},
                                "tamed": {"type": ["number", "null"]}
                            }
                        },
                        "taming_bonus": {
                            "type": "object",
                            "properties": {
                                "additive": {"type": ["number", "null"] },
                                "multiplicative": { "type": ["number", "null"] }
                            }
                        }
                    }
                },
                "torpidity": {
                    "type": "object",
                    "properties": {
                        "base": {"type": ["number", "null"]},
                        "level_increase": {
                            "type": "object",
                            "properties": {
                                "wild": {"type": ["number", "null"]},
                                "tamed": {"type": ["number", "null"]}
                            }
                        },
                        "taming_bonus": {
                            "type": "object",
                            "properties": {
                                "additive": {"type": ["number", "null"] },
                                "multiplicative": { "type": ["number", "null"] }
                            }
                        }
                    }
                }
            },
            "required": ["health", "stamina", "oxygen", "food", "weight", "melee", "movement", "torpidity"]
        },
        "tameable": {"type": "boolean"},
        "rideable": {"type": "boolean"},
        "breedable": {"type": "boolean"},
        "taming": {
            "type": ["object", "null"],
            "properties": {
                "method": {"type": ["string", "null"]},
                "kibble": {"type": ["string", "null"]}
            },
            "required": ["method", "kibble"]
        },
        "saddle": {
            "type": ["array", "object", "null"],
            "properties": {
                "name": {"type": ["string", "null"]},
                "engram_level": {"type": ["integer", "null"]}
            },
            "required": ["name", "engram_level"]
        },
        "rider_weaponry": {"type": "boolean"},
        "egg": {
            "type": ["object", "null"],
            "properties": {
                "name": {"type": ["string", "array"]},
                "incubation": {
                    "type": "object",
                    "properties": {
                        "range": {"type": "string"},
                        "incubation_range": {"type": "string"},
                        "incubation_time": {"type": "string"}
                    },
                    "required": ["range", "incubation_range", "incubation_time"]
                },
                "baby_time": {"type": "string"},
                "juvenile_time": {"type": "string"},
                "adolescent_time": {"type": "string"},
                "total_maturation": {"type": "string"},
                "breeding_interval": {"type": "string"}
            },
            "required": ["name", "incubation", "baby_time", "juvenile_time", "adolescent_time", "total_maturation", "breeding_interval"]
        },
        "drag_weight": {"type": ["number", "null"]},
        "cloneable": {"type": ["boolean", "null"]},
        "entity_id": {"type": ["string", "null"]}
    },
    "required": ["name", "dossier", "base_stats_growth", "tameable", "rideable", "breedable", "taming", "saddle", "rider_weaponry", "egg", "drag_weight", "cloneable", "entity_id"]
}

=== perpyderp/gigasaurus/assets/data/creatures/dinosaurs/oviraptor/data.json
{
    "name": "Oviraptor",
    "dossier": {
        "species": "Oviraptor philodator",
        "time": "Late Cretaceous",
        "diet": "Carnivore",
        "temperament": "Skittish",
        "wild": "Oviraptor philodator is a small-to-medium sized carnivore, common in the jungles and beaches of the Island. Despite being a carnivore, Oviraptor's main source of food is eggs, which it steals from nests. Unlike any other creature, Oviraptor seems to be able to surreptitiously steal these eggs, usually without attracting the attention of an irate mother. In an incredible feat of natural selection, Oviraptor seems to emit a chemical pheromone that affects many creatures as an aphrodisiac. Mated creatures are much more likely to…“create” new eggs while Oviraptor is around, which allows the Oviraptor to go about its business unperturbed.",
        "domesticated": "Too small to fight or ride, Oviraptor is still one of the more commonly tamed creatures on the Island. Its pheromone ensures an increased stream of eggs from nearby mated wild creatures, for breeding, eating, or cooking kibble. Oviraptor will autonomously do the dirty work of stealing eggs from other tribes or wild dinos on your behalf, without attracting unwanted attention. They also make quite adorable sounds, so many children simply like to keep them around as rather strange companions."
    },
    "base_stats_growth": {
        "health": {
            "base": 140,
            "level_increase": {
                "wild": 28,
                "tamed": 0.054
            },
            "taming_bonus": {
                "additive": 0.07
            }
        },
        "stamina": {
            "base": 120,
            "level_increase": {
                "wild": 12,
                "tamed": 0.1
            }
        },
        "oxygen": {
            "base": 150,
            "level_increase": {
                "wild": 15,
                "tamed": 0.1
            }
        },
        "food": {
            "base": 900,
            "level_increase": {
                "wild": 90,
                "tamed": 0.1
            },
            "taming_bonus": {
                "multiplicative": 0.15
            }
        },
        "weight": {
            "base": 100,
            "level_increase": {
                "wild": 2,
                "tamed": 0.04
            }
        },
        "melee": {
            "base": 12,
            "level_increase": {
                "wild": 0.6,
                "tamed": 0.017
            },
            "taming_bonus": {
                "additive": 0.14,
                "multiplicative": 0.176
            }
        },
        "movement": {
            "base": 100,
            "level_increase": {
                "wild": null,
                "tamed": 0.01
            },
            "taming_bonus": {
                "additive": 1,
                "multiplicative": 0.15
            }
        },
        "torpidity": {
            "base": 125,
            "level_increase": {
                "wild": 7.5,
                "tamed": null
            },
            "taming_bonus": {
                "additive": 0.5
            }
        }
    },
    "tameable": true,
    "rideable": false,
    "breedable": true,
    "taming": {
        "method": "Knockout",
        "kibble": null
    },
    "saddle": null,
    "rider_weaponry": false,
    "egg": {
        "name": "Oviraptor Egg",
        "incubation": {
            "range": "26 - 30 °C / 79 - 86 °F",
            "incubation_range": "28 °C / 82 °F",
            "incubation_time": "1h 8m 10.582s"
        },
        "baby_time": "2h 6m 15.757s",
        "juvenile_time": "8h 25m 3.028s",
        "adolescent_time": "10h 31m 18.785s",
        "total_maturation": "21h 2m 37.57s",
        "breeding_interval": "18h - 2d"
    },
    "drag_weight": 40,
    "cloneable": true,
    "entity_id": "Oviraptor_Character_BP_C"
}

=== perpyderp/gigasaurus/assets/data/creatures/dinosaurs/brontosaurus/data.json
{
    "name": "Brontosaurus",
    "dossier": {
        "species": "Brontosaurus lazarus",
        "time": "Late Cretaceous",
        "diet": "Herbivore",
        "temperament": "Docile",
        "wild": "Among giant creatures I've seen on the Island, Brontosaurus lazarus is larger than any sauropod I've read about. In fact, the dinosaur is so massive that it serenely ignores most other creatures. I've seen a pack of raptors tear apart small dinosaurs while Brontosaurus continues eating, seemingly oblivious to the hunting pack.",
        "domesticated": "Because of how docile it is, the Brontosaurus makes for an ideal pack animal. Peaceful tribes use it to carry incredible quantities of resources, while warring tribes use it to mobilize their army. Its size and strength make it one of the unique creatures on the Island that can support a \"platform\" saddle. Unfortunately, its enormity means that the process of taming a Brontosaurus can take a very long time. Some may think this is an Apatosaurus, Dreadnoughtus, Argentinosaurus, or some other sauropod, but this is a strange Island, and I'm the one doing the research. I'm convinced that this genus is Brontosaurus, and no one can tell me otherwise. My study, my rules."
    },
    "base_stats_growth": {
        "health": {
            "base": 2070,
            "level_increase": {
                "wild": 414,
                "tamed": 0.02508
            },
            "taming_bonus": {
                "additive": 0.07,
                "multiplicative": 0.9
            }
        },
        "stamina": {
            "base": 240,
            "level_increase": {
                "wild": 24,
                "tamed": 0.1
            }
        },
        "oxygen": {
            "base": 150,
            "level_increase": {
                "wild": 15,
                "tamed": 0.1
            }
        },
        "food": {
            "base": 10000,
            "level_increase": {
                "wild": 1000,
                "tamed": 0.1
            }
        },
        "weight": {
            "base": 1600,
            "level_increase": {
                "wild": 32,
                "tamed": 0.04
            }
        },
        "melee": {
            "base": 60,
            "level_increase": {
                "wild": 3,
                "tamed": 0.017
            },
            "taming_bonus": {
                "additive": 0.07,
                "multiplicative": 0.176
            }
        },
        "movement": {
            "base": 100,
            "level_increase": {
                "wild": null,
                "tamed": 0.02
            }
        },
        "torpidity": {
            "base": 2000,
            "level_increase": {
                "wild": 120,
                "tamed": null
            },
            "taming_bonus": {
                "additive": 0.5
            }
        }
    },
    "tameable": true,
    "rideable": true,
    "breedable": true,
    "taming": {
        "method": "Knockout",
        "kibble": "Exceptional"
    },
    "saddle": [
        {
            "name": "Bronto Saddle",
            "engram_level": 63
        },
        {
            "name": "Bronto Platform Saddle",
            "engram_level": 82
        }
    ],
    "rider_weaponry": false,
    "egg": {
        "name": "Bronto Egg",
        "incubation": {
            "range": "28 - 31 째C / 82 - 88 째F",
            "incubation_range": "30 째C / 86 째F",
            "incubation_time": "4h 59m 58.561s"
        },
        "baby_time": "9h 15m 33.331s",
        "juvenile_time": "1d 13h 2m 13.325s",
        "adolescent_time": "1d 22h 17m 46.656s",
        "total_maturation": "3d 20h 35m 33.313s",
        "breeding_interval": "18h - 2d"
    },
    "drag_weight": 1000,
    "cloneable": true,
    "entity_id": "Sauropod_Character_BP_C"
}

=== perpyderp/gigasaurus/assets/data/creatures/dinosaurs/diplodocus/data.json
{
    "name": "Diplodocus",
    "dossier": {
        "species": "Diplodocus insulaprincep",
        "time": "Late Jurassic",
        "diet": "Herbivore",
        "temperament": "Naive",
        "wild": "Despite being one of the Island's largest creatures, Diplodocus insulaprincep is among the Island's smaller sauropods. Instead of size and intelligence, Diplodocus developed faster maximum speed and greater endurance. When fully matured, it generally only reaches about half the size of the rather enormous Brontosaurus. Diplodocus is another creature whose continued survival on the Island confuses me. It's a very thick-headed and trusting animal, often to its fatal detriment. It never flees from predators until after they've attacked it repeatedly, preferring instead to make numerous fruitless attempts at friendship. For some strange reason, Diplodocus trusts humans so much that it doesn't seem to fight back against them…ever!",
        "domesticated": "Due to Diplodocus' smaller frame, it cannot support the type of \"platform\" saddle that other large creatures can. To make up for this, many tribes instead use an eleven-seater passenger saddle which enables Diplodocus to safely transport ten additional riders. These passengers often use ranged weapons to protect the creature, or to attack nearby enemies while on the move!"
    },
    "base_stats_growth": {
        "health": {
            "base": 1700,
            "level_increase": {
                "wild": 340,
                "tamed": 0.054
            },
            "taming_bonus": {
                "additive": 0.07
            }
        },
        "stamina": {
            "base": 550,
            "level_increase": {
                "wild": 55,
                "tamed": 0.1
            }
        },
        "oxygen": {
            "base": 300,
            "level_increase": {
                "wild": 30,
                "tamed": 0.1
            }
        },
        "food": {
            "base": 10000,
            "level_increase": {
                "wild": 1000,
                "tamed": 0.1
            }
        },
        "weight": {
            "base": 800,
            "level_increase": {
                "wild": 16,
                "tamed": 0.04
            }
        },
        "melee": {
            "base": 0,
            "level_increase": {
                "wild": 0,
                "tamed": 0
            },
            "taming_bonus": {
                "additive": 0.07,
                "multiplicative": 0.176
            }
        },
        "movement": {
            "base": 100,
            "level_increase": {
                "wild": null,
                "tamed": 0.01
            }
        },
        "torpidity": {
            "base": 3000,
            "level_increase": {
                "wild": 180,
                "tamed": null
            },
            "taming_bonus": {
                "additive": 0.5
            }
        }
    },
    "tameable": true,
    "rideable": true,
    "breedable": true,
    "taming": {
        "method": "Knockout",
        "kibble": "Regular"
    },
    "saddle": {
            "name": "Diplodocus Saddle",
            "engram_level": 32
    },
    "rider_weaponry": false,
    "egg": {
        "name": "Diplo Egg",
        "incubation": {
            "range": "26 - 29 °C / 79 - 84 °F",
            "incubation_range": "28 °C / 82 °F",
            "incubation_time": "4h 59m 58.561s"
        },
        "baby_time": "9h 15m 33.331s",
        "juvenile_time": "1d 13h 2m 13.325s",
        "adolescent_time": "1d 22h 17m 46.656s",
        "total_maturation": "3d 20h 35m 33.313s",
        "breeding_interval": "18h - 2d"
    },
    "drag_weight": 575,
    "cloneable": true,
    "entity_id": "Diplodocus_Character_BP_C"
}

=== perpyderp/gigasaurus/assets/data/creatures/dinosaurs/pegomastax/data.json
{
    "name": "Pegomastax",
    "dossier": {
        "species": "Pegomastax fructarator",
        "time": "Early Jurassic",
        "diet": "Herbivore",
        "temperament": "Defensive",
        "wild": "Among the bottom of the island's dinosaur food chain is a small herbivore called Pegomastax fructarator. It is content to spend all day alone, gorging itself on far more food than you might reasonably expect for a creature of its tiny stature. Its beak appears perfectly evolved for collecting food from plants while avoiding the indigestible fibrous strands. Pegomastax is likely to ignore any nearby creature and continue foraging, unless it is attacked. At which point, it turns into a very aggressive (though rather unthreatening) opponent, shrieking and wooping far above its actual threat level. You would expect a creature this small and weak to live in flocks, but Pegomastax seems to be fairly solitary in nature.",
        "domesticated": "While not pretty, and far too small to ride, tribes often keep Pegomastax around as a kind of farming aid. Its skill at scavenging means that it collects an extraordinary quantity of seeds and berries, while also handily gathering the rare Flowers, Mushrooms, and other ingredients necessary to cook up unusual concoctions."
    },
    "base_stats_growth": {
        "health": {
            "base": 120,
            "level_increase": {
                "wild": 24,
                "tamed": 0.054
            },
            "taming_bonus": {
                "additive": 0.07
            }
        },
        "stamina": {
            "base": 100,
            "level_increase": {
                "wild": 10,
                "tamed": 0.1
            }
        },
        "oxygen": {
            "base": 150,
            "level_increase": {
                "wild": 15,
                "tamed": 0.1
            }
        },
        "food": {
            "base": 450,
            "level_increase": {
                "wild": 45,
                "tamed": 0.1
            },
            "taming_bonus": {
                "multiplicative": 0.15
            }
        },
        "weight": {
            "base": 55,
            "level_increase": {
                "wild": 1.1,
                "tamed": 0.04
            }
        },
        "melee": {
            "base": 12 ,
            "level_increase": {
                "wild": 0.5,
                "tamed": 0.017
            },
            "taming_bonus": {
                "additive": 0.14,
                "multiplicative": 0.176
            }
        },
        "movement": {
            "base": 100,
            "level_increase": {
                "wild": null,
                "tamed": 0.01
            },
            "taming_bonus": {
                "additive": 0.5
            }
        },
        "torpidity": {
            "base": 30,
            "level_increase": {
                "wild": 1.8,
                "tamed": null
            },
            "taming_bonus": {
                "additive": 0.5
            }
        }
    },
    "tameable": true,
    "rideable": false,
    "breedable": true,
    "taming": {
        "method": "Passive",
        "kibble": null
    },
    "saddle": null,
    "rider_weaponry": false,
    "egg": {
        "name": "Pegomastax Egg",
        "incubation": {
            "range": "28 - 32 째C / 82 - 90 째F",
            "incubation_range": "30 째C / 86 째F",
            "incubation_time": "1h 8m 10.582s"
        },
        "baby_time": "3h 5m 11.111s",
        "juvenile_time": "12h 20m 44.444s",
        "adolescent_time": "15h 25m 55.555s",
        "total_maturation": "1d 6h 51m 51.109s",
        "breeding_interval": "18h - 2d"
    },
    "drag_weight": 20,
    "cloneable": true,
    "entity_id": "Pegomastax_Character_BP_C"
}

=== perpyderp/gigasaurus/assets/data/creatures/dinosaurs/giganotosaurus/data.json
{
    "name": "Giganotosaurus",
    "dossier": {
        "species": "Giganotosaurus furiosa",
        "time": "Late Cretaceous",
        "diet": "Carnivore",
        "temperament": "Angry",
        "wild": "Giganotosaurus furiosa is an enormous predator, larger even than the Tyrannosaurus or Spinosaurus. Getting cornered or run down by a Giganotosaurus can mean certain death for nearly any creature! Fighting a Giganotosaurus directly is never a good idea, as its rage rapidly grows with every hit it takes. With this rage, it builds increasing reserves of energy to use, making its iron-jawed bites progressively more deadly and enhancing its stamina. Add to this the fact that its huge body also enables it to take a tremendous amount of punishment, and you have a creature that is generally better avoided or outsmarted than attacked head-on.",
        "domesticated": "Taming Giganotosaurus is a dangerous prospect. Its rage reaction, even when tamed, can sometimes cause it to briefly turn on members of its own tribe. Indeed it may even throw off its rider if it has been sufficiently angered! And yet, the sheer size and immense power that the Giganotosaurus possesses means that some factions endeavor to tame it as a fear-inducing \"Capital\" beast of war, even at great risk!"
    },
    "base_stats_growth": {
        "health": {
            "base": 80000,
            "level_increase": {
                "wild": 40,
                "tamed": 0.04
            },
            "taming_bonus": {
                "additive": -63000
            }
        },
        "stamina": {
            "base": 400,
            "level_increase": {
                "wild": 0.2,
                "tamed": 0.01
            }
        },
        "oxygen": {
            "base": 150,
            "level_increase": {
                "wild": 0.375,
                "tamed": 0.025
            }
        },
        "food": {
            "base": 4000,
            "level_increase": {
                "wild": 10,
                "tamed": 0.025
            }
        },
        "weight": {
            "base": 700,
            "level_increase": {
                "wild": 7,
                "tamed": 0.01
            }
        },
        "melee": {
            "base": 500,
            "level_increase": {
                "wild": 25,
                "tamed": 0.0085
            },
            "taming_bonus": {
                "additive": -0.8,
                "multiplicative": 0.8
            }
        },
        "movement": {
            "base": 100,
            "level_increase": {
                "wild": null,
                "tamed": 0.0031
            }
        },
        "torpidity": {
            "base": 10000,
            "level_increase": {
                "wild": 600,
                "tamed": null
            }
        }
    },
    "tameable": true,
    "rideable": true,
    "breedable": true,
    "taming": {
        "method": "Knockout",
        "kibble": "Exceptional"
    },
    "saddle": {
            "name": "Giganotosaurus Saddle",
            "engram_level": 96
    },
    "rider_weaponry": false,
    "egg": {
        "name": "Giganotosaurus Egg",
        "incubation": {
            "range": "43 - 44 째C / 109 - 111 째F",
            "incubation_range": "44 째C / 111 째F",
            "incubation_time": "2d 1h 59m 45.609s"
        },
        "baby_time": "1d 23m 54.87s",
        "juvenile_time": "4d 1h 35m 39.482s",
        "adolescent_time": "5d 1h 59m 34.352s",
        "total_maturation": "10d 3h 59m 8.704s",
        "breeding_interval": "18h - 2d"
    },
    "drag_weight": 950,
    "cloneable": true,
    "entity_id": "Gigant_Character_BP_C"
}
